apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: resource
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Adam; sleep 5 ; done"]
    resources:                                            # Describes the type of resources to be used
      requests:
        memory: 64Mi # A mebibyte is 1,048,576 bytes, ex: 64Mi
        cpu: 100m         # CPU core split into 1000 units (milli = 1000), ex: 100m
      limits:
        memory: 128Mi # ex: 128Mi
        cpu: 200m  # ex: 200m
