apiVersion: v1
kind: Pod
metadata:
  name: yamlenvsecret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Adam; sleep 5 ; done"]
    env:
    - name: MYENVUSER          # env name in which value of the key is stored 
      valueFrom:
        secretKeyRef:
          name: myyamlsecret       # name of the secret created 
          key: myname                     # name of the key