apiVersion: v1
kind: Pod
metadata:
  name: yamlenvconfig
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Adam; sleep 5 ; done"]
    env:
    - name: MYENV         # env name in which value of the key is stored 
      valueFrom:
        configMapKeyRef:
          name: myyamlmap 
          key: SKILL              # name of the key
